---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: progctf-fleet
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: data
    app.kubernetes.io/part-of: the-voyage
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/component: data
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: postgres
          image: postgres:16.4-alpine@sha256:f1f7d8b34efe5a6e5a3b0c1baf3a3a1d3a0d3c6f94e5d3e9bb0f6a7b3a5b7c8d
          imagePullPolicy: IfNotPresent
          ports:
            - name: pg
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: postgres-credentials, key: username } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: postgres-credentials, key: password } }
            - name: POSTGRES_DB
              valueFrom: { secretKeyRef: { name: postgres-credentials, key: database } }
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "progctf", "-d", "progctf"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "progctf", "-d", "progctf"]
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop: [ALL]
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 20Gi
